[workspace]
members = [
    "e2e",
    "executor",
    "rwasm",
]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Dmitry Savonin <dmitry@fluentlabs.xyz>",
]
repository = "https://github.com/fluentlabs-xyz/rwasm"
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["wasm", "webassembly", "interpreter", "vm"]
categories = ["wasm", "no-std", "virtualization"]

[workspace.dependencies]
byteorder = { version = "1.5.0", default-features = false }
hashbrown = "0.15.2"
strum = { version = "0.27.1" }
strum_macros = { version = "0.27.1" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
paste = { version = "1.0", default-features = false }
num_enum = { version = "0.7.3" }
bytes = { version = "1.10.1", default-features = false }