[workspace]
members = [
    "bin",
    "codegen",
    "e2e",
    "rwasm",
    "rwasm_optimization",
]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Dmitry Savonin <dmitry@fluentlabs.xyz>",
]
repository = "https://github.com/fluentlabs-xyz/rwasm"
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["wasm", "webassembly", "interpreter", "vm"]
categories = ["wasm", "no-std", "virtualization"]

[workspace.dependencies]
byteorder = { version = "1.5.0", default-features = false }
#fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase", branch = "devel", default-features = false, features = ["evm"] }
fluentbase-sdk = { path = "../fluentbase/crates/sdk", default-features = false, features = ["evm"] }
fluentbase-runtime = { path = "../fluentbase/crates/runtime" }
hashbrown = "0.14.3"

[profile.release]
panic = "abort"
lto = true
opt-level = 2
strip = true
debug = false
debug-assertions = false
rpath = false
codegen-units = 1
