[package]
name = "rwasm"
edition = "2021"
authors = [
    "Dmitry Savonin <dmitry@fluentlabs.xyz>",
]
repository = "https://github.com/fluentlabs-xyz/rwasm"
readme = "README.md"
license = "MIT"
keywords = ["wasm", "webassembly", "interpreter", "vm"]
categories = ["wasm", "no-std", "virtualization"]

[dependencies]
wasmparser = { version = "0.100.1", package = "wasmparser-nostd", default-features = false }
hashbrown = { version = "0.15.2", features = ["alloc"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
paste = { version = "1.0", default-features = false }
num_enum = { version = "0.7.3", default-features = false }
bytes = { version = "1.10.1", default-features = false }
downcast-rs = { version = "2.0.1", default-features = false, features = ["sync"] }
bincode = { version = "2.0.1", default-features = false, features = ["alloc", "derive"] }
num-traits = { version = "0.2", default-features = false }
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
libm = "0.2.1"
serde = {version = "*",features = ["derive"]}
# an rwasm legacy dependency
rwasm-legacy = { path = "./legacy", default-features = false }

[dev-dependencies]
rand = "0.9.1"

[features]
default = ["std"]
std = [
    "num_enum/std",
    "bytes/std",
    "bincode/std",
    "num-traits/std",
    "bitvec/std",
    "rwasm-legacy/std",
]
more-max-pages = []
debug-print = []
