use crate::{InstructionSet, TrapCode};

impl InstructionSet {
    /// Performs an unsigned 64-bit division using only 32-bit arithmetic,
    /// returning the 64-bit quotient as two `u32` limbs (low, high).
    ///
    /// This routine emulates a full 64-bit division in environments that lack native 64-bit
    /// division instructions, such as custom virtual machines or WebAssembly VMs restricted to
    /// 32-bit stack elements.
    ///
    /// # Arguments
    /// - `n_lo`, `n_hi`: Low and high 32 bits of the dividend (`n = (n_hi << 32) | n_lo`)
    /// - `d_lo`, `d_hi`: Low and high 32 bits of the divisor  (`d = (d_hi << 32) | d_lo`)
    ///
    /// # Returns
    /// - `(q_lo, q_hi)`: Low and high 32 bits of the quotient
    ///
    /// # Algorithm
    /// - Handles corner cases: division by zero traps via `core::intrinsics::breakpoint()`, and
    ///   division producing zero quotient (when dividend < divisor).
    /// - Fast path: When divisor fits in 32 bits (`d_hi == 0`), uses a custom loop-based 64-by-32
    ///   division for efficiency.
    /// - General path: For arbitrary 64-bit divisors, performs classic binary long division over 64
    ///   iterations, building up quotient and remainder bitwise using only 32-bit arithmetic.
    ///
    /// # Panics / Traps
    /// - Division by zero triggers a breakpoint (trap/abort).
    ///
    /// # Note
    /// This function does **not** return the remainder(); it only computes the quotient.
    /// The input/output layout matches WebAssembly’s typical two-limb calling convention
    /// for 64-bit arithmetic implemented on 32-bit platforms.
    ///
    /// Max stack height: 15
    pub fn op_i64_div_u(&mut self) {
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_i32_const(0);
        self.op_local_get(8);
        self.op_br_if_nez(138);
        self.op_local_get(9);
        self.op_br_if_nez(2);
        self.op_trap(TrapCode::IntegerDivisionByZero);
        self.op_local_get(10);
        self.op_br_if_nez(9);
        self.op_i32_const(0);
        self.op_local_set(7);
        self.op_i32_const(0);
        self.op_local_set(6);
        self.op_local_get(11);
        self.op_local_get(10);
        self.op_i32_lt_u();
        self.op_br_if_nez(231);
        self.op_i32_const(0);
        self.op_local_set(7);
        self.op_i32_const(63);
        self.op_local_set(5);
        self.op_i32_const(0);
        self.op_local_set(4);
        self.op_local_get(4);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_set(4);
        self.op_local_get(5);
        self.op_i32_const(31);
        self.op_i32_gt_u();
        self.op_br_if_nez(23);
        self.op_local_get(10);
        self.op_local_get(6);
        self.op_i32_shr_u();
        self.op_i32_const(1);
        self.op_i32_and();
        self.op_local_get(5);
        self.op_i32_or();
        self.op_local_tee(5);
        self.op_local_get(10);
        self.op_i32_lt_u();
        self.op_br_if_nez(26);
        self.op_local_get(4);
        self.op_local_get(10);
        self.op_i32_sub();
        self.op_local_set(4);
        self.op_local_get(7);
        self.op_i32_const(1);
        self.op_local_get(7);
        self.op_i32_shl();
        self.op_i32_or();
        self.op_local_set(7);
        self.op_br(15);
        self.op_local_get(4);
        self.op_local_get(10);
        self.op_i32_lt_u();
        self.op_br_if_nez(11);
        self.op_local_get(4);
        self.op_local_get(10);
        self.op_i32_sub();
        self.op_local_set(4);
        self.op_i32_const(1);
        self.op_local_get(6);
        self.op_i32_shl();
        self.op_local_get(8);
        self.op_i32_or();
        self.op_local_set(7);
        self.op_local_get(5);
        self.op_i32_const(-1);
        self.op_i32_add();
        self.op_local_tee(6);
        self.op_i32_const(-1);
        self.op_i32_ne();
        self.op_br_if_nez(-50);
        self.op_i32_const(0);
        self.op_local_set(6);
        self.op_i32_const(63);
        self.op_local_set(5);
        self.op_i32_const(0);
        self.op_local_set(10);
        self.op_local_get(10);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_set(10);
        self.op_local_get(5);
        self.op_i32_const(31);
        self.op_i32_gt_u();
        self.op_br_if_nez(23);
        self.op_local_get(11);
        self.op_local_get(6);
        self.op_i32_shr_u();
        self.op_i32_const(1);
        self.op_i32_and();
        self.op_local_get(11);
        self.op_i32_or();
        self.op_local_tee(11);
        self.op_local_get(10);
        self.op_i32_lt_u();
        self.op_br_if_nez(35);
        self.op_local_get(10);
        self.op_local_get(10);
        self.op_i32_sub();
        self.op_local_set(10);
        self.op_local_get(6);
        self.op_i32_const(1);
        self.op_local_get(7);
        self.op_i32_shl();
        self.op_i32_or();
        self.op_local_set(6);
        self.op_br(24);
        self.op_local_get(4);
        self.op_local_get(6);
        self.op_i32_shr_u();
        self.op_i32_const(1);
        self.op_i32_and();
        self.op_local_get(11);
        self.op_i32_or();
        self.op_local_tee(11);
        self.op_local_get(10);
        self.op_i32_lt_u();
        self.op_br_if_nez(13);
        self.op_local_get(10);
        self.op_local_get(10);
        self.op_i32_sub();
        self.op_local_set(10);
        self.op_i32_const(1);
        self.op_local_get(6);
        self.op_i32_const(31);
        self.op_i32_and();
        self.op_i32_shl();
        self.op_local_get(7);
        self.op_i32_or();
        self.op_local_set(6);
        self.op_local_get(5);
        self.op_i32_const(-1);
        self.op_i32_add();
        self.op_local_tee(6);
        self.op_i32_const(-1);
        self.op_i32_ne();
        self.op_br_if_nez(-59);
        self.op_br(107);
        self.op_i32_const(0);
        self.op_local_set(7);
        self.op_local_get(10);
        self.op_local_get(9);
        self.op_i32_ge_u();
        self.op_br_if_nez(4);
        self.op_i32_const(0);
        self.op_local_set(6);
        self.op_br(98);
        self.op_local_get(11);
        self.op_local_get(10);
        self.op_i32_ge_u();
        self.op_br_if_nez(7);
        self.op_i32_const(0);
        self.op_local_set(6);
        self.op_local_get(10);
        self.op_local_get(9);
        self.op_i32_eq();
        self.op_br_if_nez(88);
        self.op_i32_const(0);
        self.op_local_set(4);
        self.op_i32_const(64);
        self.op_local_set(3);
        self.op_i32_const(0);
        self.op_local_set(2);
        self.op_i32_const(0);
        self.op_local_set(7);
        self.op_i32_const(0);
        self.op_local_set(6);
        self.op_local_get(2);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_get(11);
        self.op_i32_const(31);
        self.op_i32_shr_u();
        self.op_i32_or();
        self.op_local_set(5);
        self.op_local_get(4);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_get(3);
        self.op_i32_const(31);
        self.op_i32_shr_u();
        self.op_i32_or();
        self.op_local_tee(5);
        self.op_local_get(9);
        self.op_i32_gt_u();
        self.op_br_if_nez(14);
        self.op_i32_const(0);
        self.op_local_set(1);
        self.op_local_get(4);
        self.op_local_get(9);
        self.op_i32_ne();
        self.op_br_if_nez(5);
        self.op_local_get(5);
        self.op_local_get(10);
        self.op_i32_ge_u();
        self.op_br_if_nez(4);
        self.op_local_get(5);
        self.op_local_set(2);
        self.op_br(15);
        self.op_local_get(4);
        self.op_local_get(9);
        self.op_i32_sub();
        self.op_local_get(6);
        self.op_local_get(11);
        self.op_i32_lt_u();
        self.op_i32_sub();
        self.op_local_set(4);
        self.op_local_get(5);
        self.op_local_get(10);
        self.op_i32_sub();
        self.op_local_set(2);
        self.op_i32_const(1);
        self.op_local_set(1);
        self.op_local_get(10);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_get(12);
        self.op_i32_const(31);
        self.op_i32_shr_u();
        self.op_i32_or();
        self.op_local_set(10);
        self.op_local_get(11);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_set(11);
        self.op_local_get(7);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_local_get(7);
        self.op_i32_const(31);
        self.op_i32_shr_u();
        self.op_i32_or();
        self.op_local_set(7);
        self.op_local_get(1);
        self.op_local_get(7);
        self.op_i32_const(1);
        self.op_i32_shl();
        self.op_i32_or();
        self.op_local_set(6);
        self.op_local_get(3);
        self.op_i32_const(-1);
        self.op_i32_add();
        self.op_local_tee(4);
        self.op_br_if_nez(-76);
        self.op_local_get(7);
        self.op_i32_const(0);
        self.op_i32_const(32);
        self.op_i32_const(0);
        self.op_local_get(2);
        self.op_i32_const(63);
        self.op_i32_and();
        self.op_local_set(2);
        self.op_local_get(2);
        self.op_br_if_eqz(32);
        self.op_local_get(2);
        self.op_i32_const(31);
        self.op_i32_gt_u();
        self.op_br_if_eqz(10);
        self.op_local_get(4);
        self.op_local_get(3);
        self.op_i32_const(32);
        self.op_i32_sub();
        self.op_i32_shl();
        self.op_local_set(3);
        self.op_i32_const(0);
        self.op_local_set(4);
        self.op_br(19);
        self.op_local_get(4);
        self.op_local_get(3);
        self.op_i32_shl();
        self.op_local_set(4);
        self.op_local_get(3);
        self.op_local_get(3);
        self.op_i32_shl();
        self.op_local_set(3);
        self.op_local_get(4);
        self.op_i32_const(32);
        self.op_local_get(4);
        self.op_i32_const(31);
        self.op_i32_and();
        self.op_i32_sub();
        self.op_i32_shr_u();
        self.op_local_get(4);
        self.op_i32_or();
        self.op_local_set(3);
        self.op_drop();
        self.op_drop();
        self.op_local_get(8);
        self.op_i32_const(0);
        self.op_local_get(3);
        self.op_i32_or();
        self.op_local_set(2);
        self.op_local_get(3);
        self.op_i32_or();
        self.op_local_set(2);
        self.op_local_set(11);
        self.op_local_set(11);
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
        self.op_drop();
    }
}
