[package]
name = "rwasm_optimization"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rwasm-codegen = { path = "../codegen", default-features = false }
#rwasm-codegen = { git = "https://github.com/fluentlabs-xyz/rwasm", branch = "devel", default-features = false }
fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase", branch = "devel", default-features = false }
lol_alloc = "0.4.0"

[dev-dependencies]
wat = { version = "1" }
fluentbase-runtime = { git = "https://github.com/fluentlabs-xyz/fluentbase", branch = "devel" }

[features]
default = []
std = ["fluentbase-sdk/runtime"]
e2e = []
